---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex-secondary
spec:
  destination:
    name: osc-cl1
    namespace: dex-secondary
  project: os-climate
  source:
    path: dex/overlays/osc/osc-cl1-secondary
    repoURL: https://github.com/os-climate/ops-argocd.git
    targetRevision: main
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #     - Validate=false
