---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opendatahub-operator
spec:
  destination:
    name: osc-cl1
    namespace: opendatahub-operator
  project: os-climate
  source:
    path: odh-operator/overlays/osc/osc-cl1
    repoURL: https://github.com/os-climate/ops-argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
