apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
spec:
  project: os-climate
  source:
    repoURL: https://github.com/os-climate/ops-argocd.git
    targetRevision: main
    path: reloader/overlays/osc/osc-cl1
  destination:
    name: osc-cl1
    namespace: reloader
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #     - Validate=false
