apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-secret
spec:
  secretStoreRef:
    name: osc-vault-store
    kind: SecretStore
  target:
    name: mysql-secret
  dataFrom:
    - extract:
        key: osc/osc-cl2/kubeflow/mysql-secret
