apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secret-config
spec:
  secretStoreRef:
    name: osc-vault-store
    kind: SecretStore
  target:
    name: grafana-secret-config
  dataFrom:
    - extract:
        key: osc/osc-cl2/opf-monitoring/grafana-secret-config
