issuer: https://dex-dex.apps.osc-cl3.eqcq.p1.openshiftapps.com

storage:
  type: memory

web:
  http: "0.0.0.0:5556"

grpc:
  addr: "0.0.0.0:5557"

telemetry:
  http: "0.0.0.0:5558"

oauth2:
  skipApprovalScreen: true
  alwaysShowLoginScreen: false
  responseTypes: ["code", "token", "id_token"]

staticClients:
  - id: vault
    name: Vault
    redirectURIs:
      - https://vault-ui-vault.apps.osc-cl3.eqcq.p1.openshiftapps.com/ui/vault/auth/oidc/oidc/callback
      - https://vault-ui-vault.apps.osc-cl3.eqcq.p1.openshiftapps.com:8250/oidc/callback
      - http://localhost:8250/oidc/callback
    secretEnv: VAULT_STAGING_SECRET

connectors:
  - type: openshift
    id: openshift
    name: OpenShift
    config:
      issuer: https://kubernetes.default.svc
      clientID: system:serviceaccount:dex:dex
      clientSecret: $OPENSHIFT_CLIENT_SECRET
      redirectURI: https://dex-dex.apps.osc-cl3.eqcq.p1.openshiftapps.com/callback
      groups:
        - system:authenticated
