apiVersion: kustomize.config.k8s.io/v1beta1
components:
- ../../../../components/project-admin-rolebindings/thoth-devops
- ../../../../components/project-admin-rolebindings/osc
- ../../../../components/monitoring-rbac
- ../../../../components/limitranges/default
kind: Kustomization
namespace: osc-ci-prow
resources:
- namespace.yaml
- resourcequota.yaml
