apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jupyterhub-api-token
spec:
  secretStoreRef:
    name: osc-vault-store
    kind: SecretStore
  target:
    name: jupyterhub-api-token
  dataFrom:
    - extract:
        key: osc/osc-cl2/odh-jupyterhub/jupyterhub-api-token
