apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-projects
spec:
  destination:
    name: in-cluster
    namespace: openshift-gitops
  project: default
  source:
    path: argocd/overlays/osc-cl3/projects
    repoURL: https://github.com/os-climate/ops-argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - Validate=false
