apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: trino-secret-env
spec:
  secretStoreRef:
    name: osc-vault-store
    kind: SecretStore
  target:
    name: trino-secret-env
  dataFrom:
    - extract:
        key: osc/osc-cl2/odh-trino/trino-secret-env
