apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: data-science
  labels:
    project-template: global
spec:
  destinations:
    - namespace: 'ds-*'
      server: 'https://api.odh-cl1.apps.os-climate.org:6443'
    - namespace: 'ds-*'
      server: 'https://api.odh-cl2.apps.os-climate.org:6443'
    - namespace: 'openshift-gitops'
      server: 'https://api.osc-cl3.eqcq.p1.openshiftapps.com:6443'
  sourceRepos:
    - '*'
  roles:
    - name: project-admin
      description: Read/Write access to this project only
      policies:
        - p, proj:data-science:project-admin, applications, get, data-science/*, allow
        - p, proj:data-science:project-admin, applications, create, data-science/*, allow
        - p, proj:data-science:project-admin, applications, update, data-science/*, allow
        - p, proj:data-science:project-admin, applications, delete, data-science/*, allow
        - p, proj:data-science:project-admin, applications, sync, data-science/*, allow
        - p, proj:data-science:project-admin, applications, override, data-science/*, allow
        - p, proj:data-science:project-admin, applications, action/*, data-science/*, allow
      groups:
        - data-science
        - osc
