apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: trino-secret-files
spec:
  secretStoreRef:
    name: osc-vault-store
    kind: SecretStore
  target:
    name: trino-secret-files
  dataFrom:
    - extract:
        key: osc/osc-cl1/odh-trino/trino-secret-files
