---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: peribolos-as-a-service
spec:
  destination:
    name: in-cluster
    namespace: peribolos-as-a-service
  project: osc-infra
  source:
    path: manifests/overlays/prod
    repoURL: https://github.com/operate-first/peribolos-as-a-service.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
