apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: osc-ops@lists.os-climate.org
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - dns01:
          route53:
            accessKeyID: AKIAZNQ2HXS5LH5RULMV
            hostedZoneID: Z04490453K6YE8HM7YHJ6
            region: us-east-1
            secretAccessKeySecretRef:
              key: secret-access-key
              name: route53-aws-key
        selector:
          dnsZones:
            - apps.os-climate.org
