apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: route53
spec:
    secretStoreRef:
        name: osc-vault-store
        kind: SecretStore
    target:
        name: route53
    dataFrom:
        - extract:
              key: osc/osc-cl1/openshift-ingress/route53
