apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: route53-aws-key
spec:
    secretStoreRef:
        name: osc-vault-store
        kind: SecretStore
    target:
        name: route53-aws-key
    dataFrom:
        - extract:
              key: osc/osc-cl2/openshift-cert-manager/route53-aws-key
