apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-token
spec:
  secretStoreRef:
    name: osc-vault-store
    kind: SecretStore
  refreshInterval: "1h"
  target:
    name: github-token
  dataFrom:
    - extract:
        key: osc/osc-cl3/osc-ci-prow/github-token
