apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hmac-token
spec:
  secretStoreRef:
    name: osc-vault-store
    kind: SecretStore
  refreshInterval: "1h"
  target:
    name: hmac-token
  dataFrom:
    - extract:
        key: osc/osc-cl3/osc-ci-prow/hmac-token
