apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ssh-secret
spec:
  secretStoreRef:
    name: osc-vault-store
    kind: SecretStore
  refreshInterval: "1h"
  target:
    name: ssh-secret
  dataFrom:
    - extract:
        key: osc/osc-cl3/osc-ci-prow/ssh-secret
