---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  destination:
    name: osc-cl2
    namespace: opf-monitoring
  project: osc-infra
  source:
    path: grafana/overlays/osc/osc-cl2
    repoURL: https://github.com/os-climate/ops-argocd.git
    targetRevision: main
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #   - Validate=false
