apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - acme-operator.yaml
  - cloudbeaver.yaml
  - cluster-resources.yaml
  - das.yaml
  - das-openmetadata.yaml
  - dex-secondary.yaml
  - dex.yaml
  - external-secrets.yaml
  - grafana.yaml
  - jh-idle-culler.yaml
  - k8s-annotations-exporter.yaml
  - kafka.yaml
  - kepler.yaml
  - kfdefs.yaml
  - kfp-tekton.yaml
  - odh-operator.yaml
  - openmetadata.yaml
  - pachyderm.yaml
  - reloader.yaml
