apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  destination:
    name: in-cluster
    namespace: external-secrets-operator
  project: cluster-management
  source:
    path: external-secrets/overlays/osc/osc-cl3
    repoURL: https://github.com/os-climate/ops-argocd.git
    targetRevision: main
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #     - Validate=false
