apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: superset-custom
spec:
  secretStoreRef:
    name: osc-vault-store
    kind: SecretStore
  target:
    name: superset-custom
  dataFrom:
    - extract:
        key: osc/osc-cl2/odh-superset/superset-custom
