apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pachyderm-aws
spec:
  secretStoreRef:
    name: osc-vault-store
    kind: SecretStore
  target:
    name: pachyderm-aws
  dataFrom:
    - extract:
        key: osc/osc-cl2/pachyderm/pachyderm-aws
