plank:
  report_templates:
    "*": "[Full PR test history](https://prow.apps.osc-cl3.eqcq.p1.openshiftapps.com/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}). [Your PR dashboard](http://prow.apps.osc-cl3.eqcq.p1.openshiftapps.com/pr?query=is%3Apr%20state%3Aopen%20author%3A{{with index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}). Please help us and [open an issue](https://github.com/{{.Spec.Refs.Org}}/{{.Spec.Refs.Repo}}/issues?q=is:issue+is:open) when you hit one in your PR."
  job_url_prefix_config:
    "*": http://prow.apps.osc-cl3.eqcq.p1.openshiftapps.com/view/
  default_decoration_configs:
    "*":
      gcs_configuration:
        bucket: s3://prow-storage/prow-logs
        path_strategy: explicit
      s3_credentials_secret: s3-credentials
      ssh_key_secrets:
        - ssh-secret
      utility_images:
        clonerefs: clonerefs
        entrypoint: entrypoint
        initupload: initupload
        sidecar: sidecar
sinker:
  max_pod_age: 6h
  max_prowjob_age: 12h
  resync_period: 1m
  terminated_pod_ttl: 120m

prowjob_namespace: osc-ci-prow
pod_namespace: osc-ci-prow
log_level: debug

in_repo_config:
  enabled:
    os-climate: true

  allowed_clusters:
    "os-climate": ["https://api.osc-cl3.eqcq.p1.openshiftapps.com:6443"]

branch_cleaner:
  preserved_branches:
    os-climate:
      - main
      - master

branch-protection:
  allow_disabled_policies: true
  orgs:
    os-climate:
      protect: false
      repos:
        aicoe-osc-demo:
          protect: true
          allow_force_pushes: false
          required_status_checks:
            contexts:
              - aicoe-ci/prow/pre-commit
          include:
            - "^master"
            - "^main"
          restrictions:
            users: []
            teams:
              - sourceops
            required_pull_request_reviews:
              dismiss_stale_reviews: false
              required_approving_review_count: 1

deck:
  skip_storage_path_validation: false
  spyglass:
    size_limit: 100000000
    # 100MB
    # gcs_browser_prefix: https://gcsweb.k8s.io/gcs/
    # testgrid_config: gs://k8s-testgrid/config
    # testgrid_root: https://testgrid.k8s.io/
    lenses:
      - lens:
          name: metadata
        required_files:
          - ^(?:started|finished)\.json$
        optional_files:
          - ^(?:podinfo|prowjob)\.json$
      - lens:
          name: buildlog
          config:
            highlight_regexes:
              - timed out
              - "ERROR:"
              - (FAIL|Failure \[)\b
              - panic\b
              - ^E\d{4} \d\d:\d\d:\d\d\.\d\d\d]
              - "^INFO: Analyzed \\d+ targets"
        required_files:
          - ^.*build-log\.txt$
      - lens:
          name: podinfo
        required_files:
          - ^podinfo\.json$
  additional_allowed_buckets:
    - prow-storage
  tide_update_period: 1s

tide:
  sync_period: 2m

  pr_status_base_urls:
    "*": http://prow.apps.osc-cl3.eqcq.p1.openshiftapps.com/pr

  merge_method:
    os-climate: merge

  queries:
    - orgs:
        - os-climate
      labels:
        - approved
        - lgtm
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase

  blocker_label: tide/merge-blocker
  squash_label: tide/merge-method-squash
  rebase_label: tide/merge-method-rebase
  merge_label: tide/merge-method-merge

  context_options:
    from-branch-protection: true
    skip-unknown-contexts: true
    orgs:
      operate-first: #not sure about this may need
        repos:
          peribolos-as-a-service:
            skip-unknown-contexts: false
          probot-extensions:
            skip-unknown-contexts: false
          probot-template:
            skip-unknown-contexts: false
